# Generated by Django 5.0 on 2024-01-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=75)),
                ('cedula', models.CharField(max_length=13)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=80)),
                ('contrasena', models.CharField(max_length=80)),
                ('imagen_cedula', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_prestada', models.IntegerField()),
                ('cuotas', models.IntegerField()),
                ('monto_cuotas', models.IntegerField()),
                ('total_pagar', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrestamosTaveras.registrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='PagosRealizados',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=13)),
                ('monto_pagado', models.IntegerField()),
                ('cuotas_pagadas', models.IntegerField()),
                ('redito', models.IntegerField()),
                ('fecha', models.DateField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrestamosTaveras.registrousuario')),
            ],
        ),
    ]
